### ISSUE TITLE
Arduino Port?

### ISSUE THREAD

**Issue by Vission01** [turgu1/bt-keyboard#3]
Would it be possible to port this to Arduino?

**Comment by turgu1** [comment]
I don't know. The last time I looked at the Arduino Bluetooth software for the ESP32, it didn't seem easy. I'm not an expert on the Arduino side so you may have to find somebody more knowledgeable about Bluetooth on that side.

**Comment by Hamberthm** [comment]
My fork is working on Arduino IDE. Only change I made to make it work is changing the Bluetooth start commands in the Setup method of the class to btStart().  [https://github.com/Hamberthm/bt-keyboard](https://github.com/Hamberthm/bt-keyboard)

**Comment by turgu1** [comment]
Thanks for the info. I’m glad you made it works!
